name: Build IceShot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  daemon:
    name: Build Daemon
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build Project
        run: make -C daemon debug
  worker:
    name: Build Worker
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Odin
        uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Project
        run: make -C worker debug
